Migrate CSV upload page
teamforus/forus-frontend-react pull request #100
Opened 2024-03-28 08:36 UTC by aghimpu

2024-03-28 10:04 UTC, lexlog commented on react/src/dashboard/components/pages/csv_validations/elements/CSVUpload.tsx
> +                        return key.indexOf('_eligible') === key.length - 9;
@aghimpu could this be actual?

2024-05-13 08:21 UTC, lexlog commented
note - third to test

2024-05-16 15:05 UTC, irinaBerendeeva87 reviewed
### QA review:

❌ During the loading of the transaction page, the Upload Transactions Batch Button appeared after other elements.
this is will be fixed in another task(https://github.com/teamforus/forus-frontend-react/pull/76)

https://github.com/teamforus/forus-frontend-react/assets/55141843/7e691bca-8f84-48c8-8dee-f9f85943f2f0

❌ Not appeared the button "Make a bulk transaction now" after the CSV file was uploaded. 

❌ When deleting a selected file before uploading, the Upload button is displayed.
<img width="728" alt="Screenshot 2024-05-16 at 16 13 40" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/5d8669a1-e831-44b1-8a25-d82f545c9b86">

✅ notifications when uploading the correct/ incorrect file
✅ downloading sample file 
✅ screen with successful uploading
✅ uploading via drag-and-drop of a file 
✅ uploading file from a computer
✅ error screen when "Transaction creation failed!"

2024-05-24 12:55 UTC, irinaBerendeeva87 requested changes
**Checked:**

**Activatiecode aanmaken**
❌ field in forms : 
not all fields are present  in Stadjerspas form: 
<img width="678" alt="Screenshot 2024-05-24 at 13 51 21" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/4ffff7f2-f962-4ad6-a158-01ce935d1d1a">

❌ input field validation: 
allow to Create activation code when BSN has value 1. 
<img width="792" alt="Screenshot 2024-05-24 at 14 27 04" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/781080ff-9094-4688-9873-dcd2ef43367e">

❌ Can't proceed with the form when filling in all visible fields. 
<img width="554" alt="Screenshot 2024-05-24 at 14 05 24" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/4b057a05-d60e-466f-8f3b-61e02ddbc1b0">

✅ error messages 


✅ message when "No applicant"
<img width="982" alt="Screenshot 2024-05-24 at 13 54 10" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/c7595f17-d4f9-42c8-a97d-ee502a951651">

**Drag & drop functionality**
❌ Drag & drop  functionality causes white screen and errors in the console
<img width="1254" alt="Screenshot 2024-05-24 at 14 48 57" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/4074d42b-abdd-46d2-b03c-a567e4a68089">

https://github.com/teamforus/forus-frontend-react/assets/55141843/35dfd50f-743e-420a-9df9-4d1b4cf7672e

✅ Paggination

2024-05-31 10:33 UTC, dev-rminds commented
@irinaBerendeeva87 the last commit has react.sponsor branch from backend as dependency
<img width="381" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/212962e1-53a4-47cc-ad40-ed4bb914c7af">
https://github.com/teamforus/forus-backend/pull/2135
I should fix some issues migrated from angular version like missing label/placeholder for primary key

<img width="482" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/c120c9e3-c5bb-4dad-80f6-8c3624328dc8">
<img width="486" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/e13bc401-ef49-4030-ac5e-93212f24a00c">

and record type key instead of the name in the table bellow:
<img width="168" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/8faee07e-d295-4899-97dc-ca3a9735561c">
<img width="145" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/a91f9525-0b22-4a9e-8b4a-a632805993c1">

Not sure how to reproduce:
- no error message when a sponsor with limited rights tries to delete Applicant details

For "allow to Create activation code when BSN has value 1" since it's not react related, we need to create a separate issue.

And also not react related, I think the part where you can add extra fields is not working properly:
<img width="489" alt="image" src="https://github.com/teamforus/forus-frontend-react/assets/25606248/c04d03c2-bb4b-4fcb-a327-c023bcb2d21e">

It is possible to add more records but since the api will only allow to add records which are part of the criteria, formula or 
is primary_key (which are already in the form by default and cant be removed), anything you will add as extra will not pass the validation which makes the whole feature unusable.
I think this also needs a separate issue to investigate what are the use cases and how to properly fix it.

2024-06-04 14:05 UTC, irinaBerendeeva87 requested changes
**Retested:**
❌ modal "Activatiecode aanmaken" don't have bsn_hash  in description
<img width="519" alt="Screenshot 2024-06-04 at 15 49 31" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/dafc12ef-4a09-45e8-a42e-4623f27b50ae">
✅ all fields are present in Stadjerspas form
✅  Drag & drop functionality

2024-06-07 11:12 UTC, irinaBerendeeva87 submitted a review, later dismissed
### Checked:
✅ modal "Activatiecode aanmaken" have bsn_hash in description
<img width="454" alt="Screenshot 2024-06-07 at 13 07 24" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/ba38267f-778b-4e7e-98be-3a97bdffb3cb">

2024-06-07 11:15 UTC, lexlog commented
according to error https://github.com/teamforus/forus-frontend-react/pull/100#pullrequestreview-2104290552
@dev-rminds proposed to make a fallback for missing translation

2024-06-10 14:46 UTC, irinaBerendeeva87 approved these changes

2024-06-10 14:47 UTC, merged