Add external validators
teamforus/forus-frontend-react pull request #147
Opened 2024-06-13 15:07 UTC by ateamcms

## Changes description & testing suggestions

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-06-17 17:39 UTC, lexlog approved these changes

2024-06-19 14:49 UTC, irinaBerendeeva87 requested changes
**Checked : /external-validators**

✅ Search line
✅  errors
✅ Pagination
✅ Filtering
✅ Content
❌ The table is out of the border with a smaller screen size
<img width="136" alt="Screenshot 2024-06-19 at 16 41 07" src="https://github.com/teamforus/forus-frontend-react/assets/55141843/7866607c-1909-46c6-a68c-23fe426e6726">

2024-06-20 09:37 UTC, irinaBerendeeva87 approved these changes
Approved due to no new issue

2024-06-20 09:38 UTC, lexlog commented
status - ready for merge

2024-06-21 11:26 UTC, merged