Add wcag suffix for page title
teamforus/forus-frontend-react pull request #163
Opened 2024-06-23 16:12 UTC by ateamcms

## Changes description & testing suggestions
To enable wcag suffix add to platform config (to flags list) new property wcagSuffix with text of this suffix

## Developers checklist
- [ ] *Check that dusk tests are working locally on compatible branch*
- [ ] *Mobile version of changes is developed* - if its a webshop feature, mobile version for this feature is developed

## QA checklist
- *Check regress in implementations custom css* - changes are not breaking other implementations designes
- Feature is tested in different screen sizes - desktop, mobile
- WCAG requirements are met - new feature is accessible by keyboard, there are an alt texts
- Translations are done

2024-07-16 08:13 UTC, lexlog commented
- [ ] @ateamcms could you please also add example of suffix configuration to qdt-env example

2024-07-17 14:06 UTC, ateamcms commented
added page title suffix to cms, also there is pr on backend https://github.com/teamforus/forus-backend/pull/2256

2024-07-17 14:59 UTC, dev-rminds commented on react/src/dashboard/components/pages/implementations-cms/ImplementationsCms.tsx
> +                                <div className="form-group form-group-inline form-group-inline-xl tooltipped">
@ateamcms could you please replace this info block with this component? 
[react/src/dashboard/components/elements/forms/elements/FormGroupInfo.tsx](https://github.com/teamforus/forus-frontend-react/blob/develop/react/src/dashboard/components/elements/forms/elements/FormGroupInfo.tsx)

2024-07-17 19:23 UTC, ateamcms commented on react/src/dashboard/components/pages/implementations-cms/ImplementationsCms.tsx
> +                                <div className="form-group form-group-inline form-group-inline-xl tooltipped">
replaced

2024-07-18 09:45 UTC, irinaBerendeeva87 submitted a review, later dismissed
### Checked:
✅ Browser tab postfix
<img width="619" alt="Screenshot 2024-07-18 at 11 44 59" src="https://github.com/user-attachments/assets/59b7a010-6bdb-4abd-b5e0-3835903a76f3">

**Titles in Nijmegen**
✅ /fondsen-aanvraag: 
✅ Login page 

**Titles in Noordoostpolder**
✅ Login page 
✅ Aanvragen( /fondsen-aanvraag):
✅ Meedoenpakket: 
✅/aanbod/203: Aanbod 

**Titles in Goeree-Overflakkee**
✅ Login page
✅ Aanbod 
✅ Aanvragen( /fondsen-aanvraag)

2024-07-18 10:30 UTC, lexlog requested changes
https://github.com/teamforus/forus-frontend-react/pull/163#issuecomment-2236166544

2024-07-18 12:33 UTC, lexlog approved these changes

2024-07-18 12:33 UTC, merged